on: 
    repository_dispatch:
        types: [incident_report]

jobs:
    handle-incident:
        runs-on: ubuntu-latest
        steps:
            - name: Send Slack Notification
              run: echo "Incident reported."